apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: webserver
      labels:
        app: web
    spec:
      containers:
        - name: web-container
          image: nginx
          ports:
            - containerPort: 80
